#! /bin/sh

#	          o     |                   o|        |     
#	,---.,---..,---.|--- ,---.,---.,---..|    ,---|,---.
#	|   |,---||`---.|    |    |   ||   |||    |   ||   |
#	|---'`---^``---'`---'`    `---'`---|``---'`---'`---'
#	|                              `---'                

                                            
pgrep -x sxhkd > /dev/null || sxhkd &

# Configurando BSPWM
bspc monitor -d HDMI-0 1 2 3 4
# bspc monitor -d 1 2 3 4
bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config split_ratio          0.5
bspc config border_width         1
bspc config window_gap           15
bspc config borderless_monocle    true
bspc config focus_follows_pointer true
bspc config gapless_monocle       true

# Cores das bordas
bspc config focused_border_color  "#5e81ac"
bspc config normal_border_color   "#3b4252"

# Setando o cursor 
xsetroot -cursor_name left_ptr

# Programas que iniciam com o BSPWM 
picom --experimental-backend &
~/.fehbg &
dunst &
#lxqt-policykit-agent &
