#!/bin/sh


sudo updatedb
echo "Base de dados atualizada."

read -p "String: " app

local=$(locate -i $app | fzf)

echo "Selecione a opção:"
echo "1. Copiar"
echo "2. Mover"

read opcao

case $opcao in
	1) rsync -ah --info=progress2 $local .;;
	
	2) mv -v $local .;;

	*) echo "Opção inválida."
esac
